### ISSUE TITLE
fastxpub in browser

### ISSUE THREAD

**Issue by dylanseago** [trezor/hd-wallet#18]
When using webpack worker-loader with fastxpub.js the following error message comes up during the build:

```
ERROR in ./node_modules/hd-wallet/lib/fastxpub/fastxpub.js
Module not found: Error: Can't resolve 'fs' in './node_modules/hd-wallet/lib/fastxpub'
@ ./node_modules/hd-wallet/lib/fastxpub/fastxpub.js 15:417-430
```

It looks like something that uses both fs and path is being included in the browserified output

**Comment by karelbilek** [comment]
Yeah, that is some magic from emscripten that I could not remove when I tried

I remember I had some problems with that too, but then I solved it - I don't load fastxpub by worker loader at all, because worker-loader parses the .js and tries to put it through babel etc; in web wallet I just copy the file and use the worker directly (`new Worker("./fastxpub.js")`)

I also do some terrible hacking here - https://github.com/trezor/hd-wallet/blob/master/test/discovery.js#L44 (I was glad I got it working in both node and karma)

Maybe it is possible to tell workerLoader to not do parsing of the js and just use it as is?

**Comment by karelbilek** [comment]
setting up emscripten + webworkers + wepack is hell

If it didn't add significant performance boost for the xpub generation, I would remove it, but it makes the math really fast :/

**Comment by dylanseago** [comment]
I was able to get rid of the error by adding this to my webpack config :)
```javascript
node: {
  fs: "empty"
}
```

**Comment by dylanseago** [comment]
Here's what I did to get this all working with webpack:
- Added [worker-loader](https://github.com/go-faast/faast-portfolio/blob/4f7a09607add2255dc602e1d344ceef3abb39e2f/webpack.config.js#L52) webpack rule
- Added [file-loader](https://github.com/go-faast/faast-portfolio/blob/4f7a09607add2255dc602e1d344ceef3abb39e2f/webpack.config.js#L73) webpack rule for wasm
- [Ignored fs module](https://github.com/go-faast/faast-portfolio/blob/4f7a09607add2255dc602e1d344ceef3abb39e2f/webpack.config.js#L47)
- [Import and set up workers](https://github.com/go-faast/faast-portfolio/blob/4f7a09607add2255dc602e1d344ceef3abb39e2f/src/services/Bitcore.js#L6)

**Comment by karelbilek** [comment]
NICE! Thx for info
